### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by isarwarfp** [vi-kas/globomantics-cf-backend#1]
On following project setup instructions;

```
➜globomantics-cf-backend/modules/module_3(master)» sbt run                                                                                                     [17:45:03]
[info] Loading global plugins from /Users/imransarwar/.sbt/1.0/plugins
[info] Loading project definition from /Users/imransarwar/git/globomantics-cf-backend/modules/module_3/project
[info] Updating ProjectRef(uri("file:/Users/imransarwar/git/globomantics-cf-backend/modules/module_3/project/"), "module_3-build")...
[info] Done updating.
error: error while loading String, class file '/modules/java.base/java/lang/String.class' is broken
(class java.lang.NullPointerException/null)
[error] java.io.IOError: java.lang.RuntimeException: /packages cannot be represented as URI
[error] 	at java.base/jdk.internal.jrtfs.JrtPath.toUri(JrtPath.java:176)
[error] 	at scala.tools.nsc.classpath.JrtClassPath.asURLs(DirectoryClassPath.scala:204)
[error] 	at scala.tools.nsc.classpath.AggregateClassPath.$anonfun$asURLs$1(AggregateClassPath.scala:55)
[error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:240)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:937)
```

**Comment by isarwarfp** [comment]
I have import the project successfully with jdk 8 but still sbt run on intellij gets failed
```
java -version                                                                                               [17:48:44]
openjdk version "13.0.2" 2020-01-14
OpenJDK Runtime Environment (build 13.0.2+8)
OpenJDK 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)
```
and 

```
scala -version                                                                                              [17:48:47]
Scala code runner version 2.13.1 -- Copyright 2002-2019, LAMP/EPFL and Lightbend, Inc.
```

**Comment by vi-kas** [comment]
Would you share what's the error you're getting?

**Comment by isarwarfp** [comment]
Here is the error on console

```
[error] Caused by: java.lang.RuntimeException: /packages cannot be represented as URI
[error]         at java.base/jdk.internal.jrtfs.JrtPath.toUri(JrtPath.java:176)
[error]         at scala.tools.nsc.classpath.JrtClassPath.asURLs(DirectoryClassPath.scala:213)
[error]         at scala.tools.nsc.classpath.AggregateClassPath.$anonfun$asURLs$1(AggregateClassPath.scala:64)
[error]         at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:244)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:941)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error]         at scala.collection.TraversableLike.flatMap(TraversableLike.scala:244)
[error]         at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:241)
[error]         at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
[error]         at scala.tools.nsc.classpath.AggregateClassPath.asURLs(AggregateClassPath.scala:64)
[error]         at scala.tools.nsc.typechecker.Macros.findMacroClassLoader(Macros.scala:78)
[error]         at scala.tools.nsc.typechecker.Macros.findMacroClassLoader$(Macros.scala:77)
[error]         at scala.tools.nsc.Global$$anon$4.findMacroClassLoader(Global.scala:477)
[error]         at scala.reflect.macros.runtime.MacroRuntimes.$anonfun$defaultMacroClassloaderCache$2(MacroRuntimes.scala:68)
[error]         at scala.reflect.internal.SymbolTable$perRunCaches$$anon$2.apply(SymbolTable.scala:477)
[error]         at scala.reflect.macros.runtime.MacroRuntimes.defaultMacroClassloader(MacroRuntimes.scala:70)
[error]         at scala.reflect.macros.runtime.MacroRuntimes.defaultMacroClassloader$(MacroRuntimes.scala:70)
[error]         at scala.tools.nsc.Global$$anon$4.defaultMacroClassloader(Global.scala:477)
[error]         at scala.reflect.macros.runtime.MacroRuntimes$MacroRuntimeResolver.resolveRuntime(MacroRuntimes.scala:88)
[error]         at scala.reflect.macros.runtime.MacroRuntimes.$anonfun$standardMacroRuntime$3(MacroRuntimes.scala:50)
[error]         at scala.collection.mutable.MapLike.getOrElseUpdate(MapLike.scala:209)
[error]         at scala.collection.mutable.MapLike.getOrElseUpdate$(MapLike.scala:206)
[error]         at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:82)
[error]         at scala.reflect.macros.runtime.MacroRuntimes.standardMacroRuntime(MacroRuntimes.scala:50)
[error]         at scala.reflect.macros.runtime.MacroRuntimes.standardMacroRuntime$(MacroRuntimes.scala:43)
[error]         at scala.tools.nsc.Global$$anon$4.standardMacroRuntime(Global.scala:477)
[error]         at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$14.default(AnalyzerPlugins.scala:455)
[error]         at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$14.default(AnalyzerPlugins.scala:452)
[error]         at scala.tools.nsc.typechecker.AnalyzerPlugins.invoke(AnalyzerPlugins.scala:408)
[error]         at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroRuntime(AnalyzerPlugins.scala:452)
[error]         at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroRuntime$(AnalyzerPlugins.scala:452)
[error]         at scala.tools.nsc.Global$$anon$4.pluginsMacroRuntime(Global.scala:477)
[error]         at scala.reflect.macros.runtime.MacroRuntimes.macroRuntime(MacroRuntimes.scala:37)
[error]         at scala.reflect.macros.runtime.MacroRuntimes.macroRuntime$(MacroRuntimes.scala:37)
[error]         at scala.tools.nsc.Global$$anon$4.macroRuntime(Global.scala:477)
[error]         at scala.tools.nsc.typechecker.Macros$MacroExpander.$anonfun$expand$1(Macros.scala:631)
[error]         at scala.tools.nsc.Global.withInfoLevel(Global.scala:227)
[error]         at scala.tools.nsc.typechecker.Macros$MacroExpander.expand(Macros.scala:625)
[error]         at scala.tools.nsc.typechecker.Macros$MacroExpander.apply(Macros.scala:612)
[error]         at scala.tools.nsc.typechecker.Macros.standardMacroExpand(Macros.scala:787)
[error]         at scala.tools.nsc.typechecker.Macros.standardMacroExpand$(Macros.scala:785)
[error]         at scala.tools.nsc.Global$$anon$4.standardMacroExpand(Global.scala:477)
[error]         at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$12.default(AnalyzerPlugins.scala:439)
[error]         at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$12.default(AnalyzerPlugins.scala:436)
[error]         at scala.tools.nsc.typechecker.AnalyzerPlugins.invoke(AnalyzerPlugins.scala:408)
[error]         at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroExpand(AnalyzerPlugins.scala:436)
[error]         at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroExpand$(AnalyzerPlugins.scala:436)
[error]         at scala.tools.nsc.Global$$anon$4.pluginsMacroExpand(Global.scala:477)
[error]         at scala.tools.nsc.typechecker.Macros.macroExpand(Macros.scala:776)
[error]         at scala.tools.nsc.typechecker.Macros.macroExpand$(Macros.scala:769)
[error]         at scala.tools.nsc.Global$$anon$4.macroExpand(Global.scala:477)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.vanillaAdapt$1(Typers.scala:1183)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1243)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1216)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.adaptAfterOverloadResolution(Typers.scala:1250)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1214)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5740)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.computeType(Typers.scala:5801)
[error]         at scala.tools.nsc.typechecker.Namers$Namer.assignTypeToTree(Namers.scala:1090)
[error]         at scala.tools.nsc.typechecker.Namers$Namer.valDefSig(Namers.scala:1708)
[error]         at scala.tools.nsc.typechecker.Namers$Namer.memberSig(Namers.scala:1877)
[error]         at scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1842)
[error]         at scala.tools.nsc.typechecker.Namers$Namer$ValTypeCompleter.completeImpl(Namers.scala:921)
[error]         at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete(Namers.scala:2039)
[error]         at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete$(Namers.scala:2037)
[error]         at scala.tools.nsc.typechecker.Namers$TypeCompleterBase.complete(Namers.scala:2032)
[error]         at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1542)
[error]         at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1690)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5349)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5726)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5790)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3373)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3373)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:2030)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1843)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5646)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5726)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5790)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3373)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3373)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:2030)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1843)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5646)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5726)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5790)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3373)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3373)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5356)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5649)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5726)
[error]         at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.apply(Analyzer.scala:114)
[error]         at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:448)
[error]         at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.run(Analyzer.scala:103)
[error]         at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1498)
[error]         at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1482)
[error]         at scala.tools.nsc.Global$Run.compileSources(Global.scala:1475)
[error]         at scala.tools.nsc.Global$Run.compile(Global.scala:1598)
[error]         at xsbt.CachedCompiler0.run(CompilerInterface.scala:130)
[error]         at xsbt.CachedCompiler0.run(CompilerInterface.scala:105)
[error]         at xsbt.CompilerInterface.run(CompilerInterface.scala:31)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[error]         at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
[error]         at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
[error]         at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:133)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:73)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:116)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:307)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:307)
[error]         at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:106)
[error]         at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:87)
[error]         at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:116)
[error]         at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:63)
[error]         at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:89)
[error]         at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:134)
[error]         at sbt.internal.inc.Incremental$.compile(Incremental.scala:80)
[error]         at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:67)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:311)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:269)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:159)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:238)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:69)
[error]         at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1549)
[error]         at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1523)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:830)
[error] (Compile / compileIncremental) java.io.IOError: java.lang.RuntimeException: /packages cannot be represented as URI
[error] Total time: 7 s, completed 13-Mar-2020, 10:18:49 pm

```

**Comment by vi-kas** [comment]
It seems to a problem caused by **[using macros in Scala 2.12 with JDK 13](https://github.com/scala/bug/issues/11608)**. Would you ensure from project directory java and Scala versions?

**Comment by isarwarfp** [comment]
Here are the versions details !!!
![image](https://user-images.githubusercontent.com/4415622/76700313-93ebb300-66b6-11ea-8fab-55366c5bf455.png)

**Comment by vi-kas** [comment]
Thanks Imran, project should work with JDK 8, as mentioned in the issue I referenced https://github.com/vi-kas/globomantics-cf-backend/issues/1#issuecomment-599169591

**Comment by isarwarfp** [comment]
Thanks Vikas:
For the sake of completion, I was using jdk version 13 and I switched it back to 8 and it start working, following the commands as shown.

![image](https://user-images.githubusercontent.com/4415622/76700732-bed80600-66ba-11ea-87e4-41c93b485d87.png)

might it would help others too.
